name: flutter_portal
version: 1.0.0-dev.1
description: Evolved Overlay/OverlayEntry - declarative not imperative, intuitive-context, and easy-alignment
homepage: https://github.com/fzyzcjy/flutter_portal

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.21.0'

dependencies:
  collection: ^1.15.0
  flutter:
    sdk: flutter
  vector_math: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.0.0
