name: flutter_portal
version: 0.4.0
description: Evolved Overlay/OverlayEntry - declarative not imperative, intuitive-context, and easy-alignment
homepage: https://github.com/rrousselGit/flutter_portal

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.21.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
